school_name: Binom-School Tanym, 38-улица 9/5, Астана
year: 2022
timetables:
  "1":
    text: Сабақ кестесі 1-ауысым 3-тоқсан (09.01 - 30.06)
    datefrom: "2023-01-09"
  "2":
    text: Сабақ кестесі 2-ауысым 3-тоқсан (09.01 - 30.06)
    datefrom: "2023-01-09"
