name: Website generator

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-web:
    name: Build website
    runs-on: ubuntu-latest
    environment:
      name: GitHub Actions
    permissions:
      contents: write
    steps:
      - name: Check author
        uses: actions/github-script@v3
        with:
          script: |
            if (context.payload.head_commit) {
              const author = context.payload.head_commit.author.username
            } else {
              const author = ""
            }
            if (author == "github-actions[bot]") {
              core.setFailed("Commit author is GitHub Actions")
            }
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Get .XLSX files
        id: get_xlsx_files
        run: |
          if find "timetables/*.xlsx" -quit &> /dev/null; then
            echo "contains=true" >> $GITHUB_OUTPUT
          else
            echo "contains=false" >> $GITHUB_OUTPUT
          fi
      - name: Install Python dependencies to parse .XLSX files
        if: steps.get_xlsx_files.outputs.contains == 'true'
        run: |
          python -m pip install git+https://github.com/BinomTT/edu-xlsx@v1.0
      - name: Run script
        run: python main.py
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_author: GitHub Actions [bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit_message: Update website
